### ISSUE TITLE
There was a problem adding the device: 192.168.254.XXX:6077

### ISSUE THREAD

**Issue by kogren161** [wouterdebie/locast2tuner#93]
*NOTE THAT UNCLEAR BUG REPORTS (i.e. without the information requested below like logs, settings, versions, etc) MIGHT BE CLOSED WITHOUT ANY HELP!!*

Please check https://github.com/wouterdebie/locast2tuner/releases if any breaking changes have been made before filing a bug report.

**Describe the bug**
Tuner is no longer found

**To Reproduce**

1. I am trying to add the tuner to Plex.  I have also tried to add it to Jellyfin.  This system was up and working.  I was having a problem with it needing to be restarted every so often ( every couple of days to as short as a couple of hours).  So I decided to reinstall this morning.  Now the tuner is not found.  I have never seen the Default logs.  Mine just starts and gives me a new prompt.  I liked the way it would show me what was happening at start in Locast2Dvr.  I have tried un-notating the quiet option in config, but I still don't see what is happening.  I really appreciate the work you all are doing and have liked using this software.  

This is running on a Rpi 4b connected via ethernet running headless and connecting via a remote desktop connection.

I also tried installing Locast2Tuner on my Linux Mint which is setup as a dual boot, so this was a fresh install.  I installed a Plex server on Linux as well, but this is giving the same result which is "There was a problem adding the device: 192.168.254.XXX:6077"

** Logs **
Please provide any logs that show the error.

I am unable to locate any log files

** Configuration **
Add a copy of your config. You can get a copy of your running config by opening /config in a browser (e.g http://localhost:6077/config). This will not expose your locast password. If you can't access /config, please add your config file *without* your password.

I am unable to get a log by running this command either on the Rpi or from my windows installation.  I have tried this command exactly http://localhost:6077/config as well as replacing localhoast with the IP of the Rpi.
**Environment**
What operating system and version you are using.
Raspian, also tried in Linux Mint
**Screenshots**

** Environment**
What operating system and version you are using.
I have been running in Raspian, 
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

I also tried 
Linux Mint 20 "Ulyana" - Cinnamon (64-bit) with the same results.

**Additional context**

I was having problems with Locast2Tuner needing to be restarted every once in a while, but it was working well otherwise.

**Comment by wouterdebie** [comment]
> 1. I have never seen the Default logs.  Mine just starts and gives me a new prompt.  I liked the way it would show me what was happening at start in Locast2Dvr.

locast2tuner should give you output.

Would you mind describing how you install locast2tuner? Clearly someting isn't starting at all. How do you configure locast2tuner?

**Comment by kogren161** [comment]
I have followed the process described here.  I am remoting in to my Rpi.

Running this command in terminal from a remote desktop connection
curl -s "https://wouterdebie.github.io/ppa/KEY.gpg" | sudo apt-key add -

Then
sudo curl -o /etc/apt/sources.list.d/locast2tuner.list \
   "https://wouterdebie.github.io/ppa/sources.list"
sudo apt update

then
sudo apt install locast2tuner

then these two
sudo cp /etc/locast2tuner/config.example /etc/locast2tuner/config
sudo nano edit the config /etc/locast2tuner/config 
changing the user name and password

then running these two commands

sudo systemctl enable locast2tuner
sudo systemctl start locast2tuner

I have been having to come back and run the second command from time to time.  but otherwise it had been running well.

I agree it appears not to be running.  I tried to look for it in running processes, but did not see it.

**Comment by kogren161** [comment]
pi@raspberrypi:~ $ sudo apt install locast2tuner
Reading package lists... Done
Building dependency tree       
Reading state information... Done
locast2tuner is already the newest version (0.3.2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

When I run start I get this output;

pi@raspberrypi:~ $ sudo systemctl start locast2tuner 
pi@raspberrypi:~ $

**Comment by wouterdebie** [comment]
You should be able to check `/var/log/locast2tuner/locast2tuner.log` to see what's going on.

**Comment by wouterdebie** [comment]
And to run manually you could try `/usr/bin/locast2tuner -c /etc/locast2tuner/config`. Note that this runs as the `pi` user and not the `locast2tuner` user. But you should get some output in your terminal.

**Comment by kogren161** [comment]
When I go to open /var/log/locast2tuner.log, it says "the file does not look like a text file or the file encoding is not supported.  it opens a previously opened text file instead.

**Comment by kogren161** [comment]
Yes, manually started and with feedback, but I still cannot connect to the server.

pi@raspberrypi:~ $ /usr/bin/locast2tuner -c /etc/locast2tuner/config
config selected = /etc/locast2tuner/config 
Aug 22 09:38:39.810 INFO locast2tuner 0.3.2 on Linux 5.10.52-v7l+ starting..
Aug 22 09:38:39.810 INFO UUID: 1ce0b99e-b5ea-4b19-9588-63a975d77d2b
Aug 22 09:38:39.811 INFO Logging in with XXXX@XXXX.com
Aug 22 09:38:40.438 INFO Login succeeded!
Aug 22 09:38:41.508 INFO Downloading FCC facilities
Aug 22 09:38:46.848 INFO Cached FCC facilities to /home/pi/.locast2tuner/facilities
Aug 22 09:39:04.323 INFO Loading stations for Seattle (cache: true, cache timeout: 3600, days: 8)..
Aug 22 09:39:04.360 INFO Starting http server for Seattle on http://127.0.0.1:6077
Aug 22 09:39:04.361 INFO Starting 4 workers
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/http/mod.rs:132:47
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by wouterdebie** [comment]
> When I go to open /var/log/locast2tuner.log, it says "the file does not look like a text file or the file encoding is not supported. it opens a previously opened text file instead.

That's an issue with your editor. Not sure what to do there. Use a different editor? Or use `less /var/log/locast2tuner.log`.



> thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/http/mod.rs:132:47
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

That's an actual bug. Let me fix this.

**Comment by kogren161** [comment]
when I open /var/log/locast2tuner.log in nano, I get an empty file

**Comment by kogren161** [comment]
> That's an actual bug. Let me fix this.

Thanks so much for your help.

**Comment by wouterdebie** [comment]
This is fixed in 0.3.3, which is currently building.

**Comment by kogren161** [comment]
Sweet,
Thanks again.

**Comment by kogren161** [comment]
Looks like I still have an issue.  Unless this is related to me trying to connect too much.

***@***.***:~ $ sudo apt upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  locast2tuner
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 3,928 kB of archives.
After this operation, 7,168 B disk space will be freed.
Do you want to continue? [Y/n] y
Get:1 https://wouterdebie.github.io/ppa ./ locast2tuner 0.3.3 [3,928 kB]
Fetched 3,928 kB in 6s (664 kB/s)
Reading changelogs... Done
(Reading database ... 187883 files and directories currently installed.)
Preparing to unpack .../locast2tuner_0.3.3_armhf.deb ...
Unpacking locast2tuner (0.3.3) over (0.3.2) ...
Setting up locast2tuner (0.3.3) ...
***@***.***:~ $ /usr/bin/locast2tuner -c /etc/locast2tuner/config
config selected = /etc/locast2tuner/config
Aug 22 10:23:20.262 INFO locast2tuner 0.3.3 on Linux 5.10.52-v7l+ starting..
Aug 22 10:23:20.263 INFO Consider sponsoring this project at https://github.com/sponsors/wouterdebie!
Aug 22 10:23:21.125 INFO Login succeeded!
Aug 22 10:23:22.699 INFO Using cached FCC facilities at /home/pi/.locast2tuner/facilities
Aug 22 10:23:44.061 INFO Loading stations for Seattle (cache: true, cache timeout: 3600, days: 8)..
Aug 22 10:23:44.100 INFO Starting http server for Seattle on http://127.0.0.1:6077
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 98, kind: AddrInUse, message: "Address in use" }', src/http/mod.rs:85:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted

**Comment by eiddor** [comment]
Looks like it's already running - `ps -ef | grep locast`

**Comment by kogren161** [comment]
After I saw your notes on the closed issue, I tried overriding the zip.
I got this result, which looked good.
***@***.***:~ $ /usr/bin/locast2tuner -c /etc/locast2tuner/config
config selected = /etc/locast2tuner/config
Aug 22 10:17:38.779 INFO locast2tuner 0.3.2 on Linux 5.10.52-v7l+ starting..
Aug 22 10:17:38.780 INFO UUID: 1ce0b99e-b5ea-4b19-9588-63a975d77d2b
Aug 22 10:17:38.781 INFO Logging in with ***@***.***
Aug 22 10:17:39.391 INFO Login succeeded!
Aug 22 10:17:40.440 INFO Using cached FCC facilities at /home/pi/.locast2tuner/facilities
Aug 22 10:17:40.507 INFO Tuners:
Aug 22 10:17:40.507 INFO  ++
Aug 22 10:17:40.508 INFO  ||
Aug 22 10:17:40.509 INFO  ++
Aug 22 10:17:40.509 INFO  ++
Aug 22 10:17:40.510 INFO locast2tuner started..

But I still couldn’t connect to the tuner.

From: Ken Ogren
Sent: Sunday, August 22, 2021 10:25 AM
To: wouterdebie/locast2tuner ***@***.***>
Subject: RE: [wouterdebie/locast2tuner] There was a problem adding the device: 192.168.254.XXX:6077 (#93)

Looks like I still have an issue.  Unless this is related to me trying to connect too much.

***@***.***:~ $ sudo apt upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  locast2tuner
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 3,928 kB of archives.
After this operation, 7,168 B disk space will be freed.
Do you want to continue? [Y/n] y
Get:1 https://wouterdebie.github.io/ppa ./ locast2tuner 0.3.3 [3,928 kB]
Fetched 3,928 kB in 6s (664 kB/s)
Reading changelogs... Done
(Reading database ... 187883 files and directories currently installed.)
Preparing to unpack .../locast2tuner_0.3.3_armhf.deb ...
Unpacking locast2tuner (0.3.3) over (0.3.2) ...
Setting up locast2tuner (0.3.3) ...
***@***.***:~ $ /usr/bin/locast2tuner -c /etc/locast2tuner/config
config selected = /etc/locast2tuner/config
Aug 22 10:23:20.262 INFO locast2tuner 0.3.3 on Linux 5.10.52-v7l+ starting..
Aug 22 10:23:20.263 INFO Consider sponsoring this project at https://github.com/sponsors/wouterdebie!
Aug 22 10:23:21.125 INFO Login succeeded!
Aug 22 10:23:22.699 INFO Using cached FCC facilities at /home/pi/.locast2tuner/facilities
Aug 22 10:23:44.061 INFO Loading stations for Seattle (cache: true, cache timeout: 3600, days: 8)..
Aug 22 10:23:44.100 INFO Starting http server for Seattle on http://127.0.0.1:6077
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 98, kind: AddrInUse, message: "Address in use" }', src/http/mod.rs:85:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted

**Comment by kogren161** [comment]
Found it and is working now, thanks again
